-- DROP SCHEMA IF EXISTS "Part1" ;
CREATE SCHEMA IF NOT EXISTS "Part1" AUTHORIZATION postgres;
-- SCHEMA: Part1
SET search_path TO "Part1";

-- TABLE: students --
CREATE TABLE IF NOT EXISTS students (
  student_id 		    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name  		  	TEXT NOT NULL,
  last_name   		  	TEXT NOT NULL,
  email       		  	TEXT NOT NULL UNIQUE,
  enrollment_date 		DATE
);

-- Initial Data --
INSERT INTO students (first_name, last_name, email, enrollment_date) VALUES
	('John', 'Doe', 'john.doe@example.com', '2023-09-01'),
	('Jane', 'Smith', 'jane.smith@example.com', '2023-09-01'),
	('Jim', 'Beam', 'jim.beam@example.com', '2023-09-02')
ON CONFLICT (email) DO NOTHING;

--GET ALL STUDENTS FUNCTION--
CREATE OR REPLACE FUNCTION getAllStudents()
RETURNS SETOF students
LANGUAGE plpgsql
AS $$
  BEGIN
    --SELECT full table--
    RETURN QUERY
    SELECT *
    FROM students
    ORDER BY student_id;
  END;
$$;

--ADD STUDENT FUNCTION--
CREATE OR REPLACE FUNCTION addStudent(
  n_first_name      TEXT, 
  n_last_name       TEXT, 
  n_email           TEXT, 
  n_enrollment_date DATE DEFAULT CURRENT_DATE
)
RETURNS SETOF students
LANGUAGE plpgsql
AS $$
  BEGIN
    --CHECK IF EMAIL EXISTS--
    IF EXISTS(SELECT 1 FROM students WHERE email = n_email) THEN 
      RAISE EXCEPTION 'Email % already exists', n_email;
    END IF;

    --ADDING student--
    RETURN QUERY
    INSERT INTO students (first_name, last_name, email, enrollment_date)
    VALUES (n_first_name, n_last_name, n_email, n_enrollment_date)
    RETURNING *;
  END;
$$;

--UPDATE STUDENT EMAIL FUNCTION--
CREATE OR REPLACE FUNCTION updateStudentEmail(
  n_student_id    INT, 
  n_new_email     TEXT
)
RETURNS SETOF students
LANGUAGE plpgsql
AS $$
  BEGIN
    --CHECK if student exists--
    IF NOT EXISTS (SELECT 1 FROM students WHERE student_id = n_student_id) THEN 
      RAISE EXCEPTION 'Student with ID % does not exist', n_student_id;
    END IF;

    --CHECK if email exists for another student--
    IF EXISTS (SELECT 1 FROM students WHERE email = n_new_email AND student_id != n_student_id) THEN
      RAISE EXCEPTION 'Email % already in use for another student', n_new_email;
    END IF;

    --UPDATE email--
    RETURN QUERY
    UPDATE students
    SET email = n_new_email
    WHERE student_id = n_student_id
    RETURNING *;
  END;
$$;

--DELETE STUDENT FUNCTION--
CREATE OR REPLACE FUNCTION deleteStudent(
  n_student_id  INT
)
RETURNS SETOF students
LANGUAGE plpgsql
AS $$
  BEGIN
    --CHECK if student exists--
    IF NOT EXISTS (SELECT 1 FROM students WHERE student_id = n_student_id) THEN
      RAISE EXCEPTION 'Student with ID % does not exist', n_student_id;
    END IF;

    --DELETING student--
    RETURN QUERY
    DELETE FROM students
    WHERE student_id = n_student_id
    RETURNING *;
  END;
$$;